### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#53] opened 2018-01-23 15:25 UTC
- Badges are used to inform merchants of the status of a piece of information. For example, within the order history, a badge would show “Payment Pending” if money is waiting to be sent. 
- Available in the apparent alert colour

_https://semantic-ui.com/elements/label.html_

**Comment by cristianoliveira** [comment] 2018-01-29 21:47
This one looks a good one to start helping. :)
Could I get this one?

**Comment by connor-baer** [comment] 2018-01-29 22:46
@cristianoliveira 😉

**Comment by melmdesign** [comment] 2018-01-31 14:10
Duplicate of Atom instance

**Closed by melmdesign** 2018-01-31 14:10 UTC
